<template><div class="test">
  <h1 style="color:green">Hello World</h1>
  <p>This is a simple static site generated by me</p>
</div>
<p><a href="https://github.com/Z-Spring/bookstore_press" target="_blank" rel="noopener noreferrer">murphy<ExternalLinkIcon/></a></p>
</template>
