<template><div class="test">
  <h1>Hello World</h1>
  <p>This is a simple static site generated by me</p>
</div>
<p><a href="https://z-spring.github.io/bookstore_press/" target="_blank" rel="noopener noreferrer">murphy<ExternalLinkIcon/></a></p>
</template>
